#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp(ql:quickload '() :silent t)
  (ql:quickload :cl-intbytes :silent t)
  )

(defpackage :art.rhea.koala-noosphere.gen-metadata
  (:use :cl))
(in-package :art.rhea.koala-noosphere.gen-metadata)

(defconstant +series-name+ "Koala Noosphere")
(defconstant +series-date+ "2022")
(defconstant +series-artist+ "Rhea Myers")

(defun generate-metadata (json-template token-id ipfs-image-dir)
  (let ((description (with-open-file (description-stream
                                      (format nil "descriptions/~a" token-id))
                       (read description-stream))))
    (with-open-file (metadata-stream (format nil "metadata/~a" token-id)
                                     :direction :output)
      (format metadata-stream
              json-template
              +series-name+
              token-id
              ;;+series-date+
              ;;+series-artist+
              description
              ipfs-image-dir
              token-id))))

(defun main (&rest argv)
  (let ((ipfs-image-dir (car argv))
        (token-ids (with-open-file (ids-stream "token-ids")
                     (read ids-stream)))
        (json-template (uiop:read-file-string "templates/metadata.json")))
    (check-type ipfs-image-dir string)
    (ensure-directories-exist "metadata/")
    (loop for token-id in token-ids
          do (generate-metadata json-template
                                token-id
                                ipfs-image-dir))))
;;; vim: set ft=lisp lisp:
