#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(progn ;;init forms
  (ros:ensure-asdf)
  #+quicklisp(ql:quickload '() :silent t)
  (ql:quickload :cl-intbytes :silent t)
  )

(defpackage :art.rhea.koala-noosphere.gen-descriptions
  (:use :cl))
(in-package :art.rhea.koala-noosphere.gen-descriptions)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Configuration
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defconstant +rng-filepath+
  "/dev/urandom"
  ;;"/dev/TrueRNG0"
  )

(defconstant +series-name+ "Koala Noosphere")

(defconstant +num-tokens+ 16)

(defconstant +id-length-bytes+ 32)

(defconstant +significant-bytes+
  (coerce
   (loop for n from 1 upto +id-length-bytes+
         collect n)
   'vector))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Form
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defconstant +form+
  (vector
   "red" "green" "blue" "yellow" "orange" "purple" "magenta" "cyan"
   "brown" "grey" "silver" "gold"
   "colourful" "muted" "monochrome"
   "dark" "light" "bright" "saturated"
   "neon" "plastic" "metallic" "wooden" "pixellated" "textile"
   "blurry" "sharp" "contrasty"
   "biomorphic" "mechanistic" "zoomorphic" "biomechanical" "rectilinear"
   "spiky" "smooth" "sinuous"
   "simple" "complex"
   "convex" "concave"
   "varied" "homogenous" "differentiated" "all-over"
   "three dimensional" "two dimensional"
   "sculptural" "painterly" "theatrical" "filmic"
   "expressive" "diagrammatic"
   "formal" "luxurious" "ad-hoc" "austere"
   "illusionary" "tromp l'oeil"
   "large" "small"
   "tall" "short"
   "wide" "narrow"
   "shallow" "deep"
   ))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Subject
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defconstant +subject+
  (vector
   "geology" "geography" "meteorology" "astronomy" "transport" "energy"
   "food" "zoology" "technology" "communication" "entertainment"
   "science" "art history"
   "education" "oceanography" "urbanism" "engineering" "manufacture"
   "politics" "society" "intimacy" "violence" "justice" "choreography"
   "culture" "subculture" "resistance" "radicalism" "economics"
   "the human body" "history" "portrait"
   ))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Content
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defconstant +content+
  (vector
   "ironic" "serious" "transgressive"
   "cute" "zany" "interesting"
   "spiritual" "materialist"
   "socialist" "capitalist" "anti-capitalist" "anarchistic"
   "pastoral" "revolutionary"
   "happy" "sad" "angry" "annoying" "exciting" "calm"
   "unsettling" "repulsive" "disgusting" "threatening" "disqueting"
   "appealing" "enjoyable" "pleasurable" "reassuring" "erotic"
   "tense" "relaxing" "confusing"
   "ineffable"
   "bathetic"
   "sophisticated" "challenging" "childish"
   "optimisim" "pessimism" "realism" "fantasy"
   ))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Relations
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defconstant +qualifiers+
  (vector
   "is"
   "is"
   "is"
   "is"
   "is"
   "is maybe"
   "is definitely"
   "is perhaps"
   "may be"
   "might be"
   "could be"
   "might be"
   "looks"
   "looks as if it is"
   "looks like it is"
   "seems"
   "seems to be"
   "appears"
   "appears to be"
   ))

(defconstant +continuations+
  (vector
   "This artwork"
   ""
   "Furthermore it" "Moreover it" "Additionally it"
   "As well as that,"
   "And it"
   ))

(defconstant +neighbours+
  (vector
   "the token"
   "a token"
   "no tokens"
   "none of the tokens"
   "almost no tokens"
   "almost none of the tokens"
   "very few tokens"
   "a few tokens"
   "not very many tokens"
   "some tokens"
   "many tokens"
   "very many tokens"
   "almost all the tokens immediately"
   "the token that is closest"
   ))


(defconstant +property-relations+
  (vector
   '("more" "than")
   '("less" "than")
   '("even more" "than")
   '("even less" "than")
   ))

(defconstant +spatio-temporal-relations+
  (vector
   "above"
   "below"
   "left of"
   "to the left of"
   "right of"
   "to the right of"
   "behind"
   "in front"
   "next to"
   "adjacent to"
   "near to"
   "far from"
   "close to"
   "before"
   "after"
   "following"
   "trailing"
   ))

(defconstant +subjects+
  (vector
   "it"
   "it"
   "it"
   "its centre"
   "its focal point"
   "its narrowest part"
   "its widest part"
   "its base"
   "its top"
   "its brightest part"
   "its darkest part"
   ))



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Randomness
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Fetch entropy from the filesystem source

(defun ent (significant-bytes)
  (let ((random-bytes (make-array +id-length-bytes+
                                  :element-type '(unsigned-byte 8)
                                  :initial-element 0)))
    (with-open-file (rng +rng-filepath+
                         :element-type 'unsigned-byte)
      (read-sequence random-bytes rng))
    (intbytes:octets->uint random-bytes significant-bytes)))

;; This suffers from skew, revisit.

(defun ent-random-int (exclusive-upper-range)
  (mod (ent 4) exclusive-upper-range))

(defun random-choice (choices)
  (aref choices (ent-random-int (length choices))))

(defun ent-random-significant-bytes ()
  (ent (random-choice +significant-bytes+)))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Token IDs
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun gather-token-ids ()
  ;; Use a hash-table to represent a set to avoid duplicate tokens
  (let ((id-set (make-hash-table :test 'equalp)))
    (loop while (< (hash-table-count id-set) +num-tokens+)
          do (setf (gethash (ent-random-significant-bytes) id-set)
                   t))
    ;; Gather up and return the keys
    (loop for key being the hash-keys of id-set
          collect key)))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Descriptions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defvar *descriptions* (make-hash-table))

(defun generate-form ()
  (destructuring-bind
        (property-relation property-relation-comparator)
      (random-choice +property-relations+)
    ;; ~@:( capitalizes the first word only.
    ;; ~^  adds the space only between elements.
    (format nil "~{~a~^ ~}"
            (list
             (random-choice +qualifiers+)
             property-relation
             (random-choice +form+)
             property-relation-comparator
             (random-choice +neighbours+)
             (random-choice +spatio-temporal-relations+)
             (random-choice +subjects+)))))

(defun generate-subject ()
  (destructuring-bind
        (property-relation property-relation-comparator)
      (random-choice +property-relations+)
    ;; ~@:( capitalizes the first word only.
    ;; ~^  adds the space only between elements.
    (format nil "~{~a~^ ~}"
            (list
             (random-choice +qualifiers+)
             property-relation
             (random-choice +subject+)
             property-relation-comparator
             (random-choice +neighbours+)
             (random-choice +spatio-temporal-relations+)
             (random-choice +subjects+)))))

(defun generate-content ()
  (destructuring-bind
        (property-relation property-relation-comparator)
      (random-choice +property-relations+)
    ;; ~@:( capitalizes the first word only.
    ;; ~^  adds the space only between elements.
    (format nil "~{~a~^ ~}"
            (list
             (random-choice +qualifiers+)
             property-relation
             (random-choice +content+)
             property-relation-comparator
             (random-choice +neighbours+)
             (random-choice +spatio-temporal-relations+)
             (random-choice +subjects+)))))

(defun generate-property ()
  (let ((i (ent-random-int 10)))
    (cond
      ((> i 5) (generate-form))
      ((> i 2) (generate-content))
      (t (generate-subject)))))

(defun chunk-properties (properties)
  ;; TODO
  ;; Divide the properties up into 1..5 chunks and add starters/caps/periods.
  )

(defun generate-description (token-id count)
  ;; Use a hash-table to represent a set to avoid duplicate descriptions
  ;; FIXME: also reproduce this at the description level
  (let ((description-set (make-hash-table :test 'equal)))
    (loop while (< (hash-table-count description-set) count)
          do (setf (gethash (generate-property)
                            description-set)
                   t))
    ;; Gather up the keys and format them into the description.
    ;;FIXME: Separate and save alist of id/title/desc.
    (format nil
            ;; https://gigamonkeys.com/book/a-few-format-recipes.html
            "~a token ~a ~{~#[~;~a~;~a and ~a~:;~@{~a~#[~;, and ~:;, ~]~}~]~}."
            +series-name+
            token-id
            (loop for key being the hash-keys of description-set
                  collect key))))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Main program entry point
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun main (&rest argv)
  (declare (ignorable argv))
  (let ((token-ids (gather-token-ids)))
    (with-open-file (ids-stream "token-ids" :direction :output)
      (pprint token-ids ids-stream))
    (ensure-directories-exist "descriptions/")
    (loop for token-id in token-ids
          do (with-open-file (description-stream (format
                                                  nil
                                                  "descriptions/~a"
                                                  token-id)
                                                 :direction :output)
               (pprint (generate-description token-id 10)
                       description-stream)))))
