#!/bin/sh
#|-*- mode:lisp -*-|#
#|
exec ros -Q -- $0 "$@"
|#

(progn ;;init forms
  (ros:ensure-asdf)
  (ql:quickload :cl-intbytes :silent t)
  (ql:quickload :cl-ppcre :silent t)
  )

(defpackage :art.rhea.koala-noosphere.gen-svg
  (:use :cl))
(in-package :art.rhea.koala-noosphere.gen-svg)

(defconstant +series-name+ "Koala Noosphere")
(defconstant +series-date+ "2022")
(defconstant +series-artist+ "Rhea Myers")

(defun generate-svg (svg-template token-id)
  (let* ((title (format nil
                        "~a ~a ~a ~a"
                        +series-name+
                        token-id
                        +series-date+
                        +series-artist+))
         (description (with-open-file (description-stream
                                       (format nil "descriptions/~a" token-id))
                        (read description-stream)))
         (template-with-title (ppcre:regex-replace "@TITLE"
                                                   svg-template
                                                   title))
         (template-with-title-and-desc (ppcre:regex-replace "@DESCRIPTION"
                                                            template-with-title
                                                            description)))
    (with-open-file (svg-stream (format nil "images/~a.svg" token-id)
                                :direction :output)
      (princ template-with-title-and-desc svg-stream))))

(defun generate-pdf (token-id)
  (uiop:run-program (list "inkscape"
                          (format nil "images/~a.svg" token-id)
                          (format nil "--export-pdf=images/~a.pdf"
                                  token-id))))

(defun generate-png (token-id)
  (uiop:run-program (list "inkscape"
                          (format nil "images/~a.svg" token-id)
                          "--export-dpi=600"
                          (format nil "--export-png=images/~a.png"
                                  token-id))))

(defun main (&rest argv)
  (declare (ignorable argv))
  (let ((token-ids (with-open-file (ids-stream "token-ids")
                     (read ids-stream)))
        (svg-template (uiop:read-file-string "templates/placard.svg")))
    (ensure-directories-exist "images/")
    (loop for token-id in token-ids
          do (generate-svg svg-template token-id)
          do (generate-pdf token-id)
          do (generate-png token-id))))
;;; vim: set ft=lisp lisp:
